// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title EmissionManager
 * @notice Manages weekly PAIMON token emission budget across 3 phases and 4 distribution channels
 * @dev Implements deterministic emission schedule for 352 weeks with governance-adjustable LP split
 *
 * Key Features:
 * - Three-phase emission model: Fixed → Exponential Decay → Fixed
 * - Four-channel budget allocation: Debt, LP Pairs, Stability Pool, Eco
 * - Governance-adjustable LP secondary split (lpPairs vs stabilityPool)
 * - Gas-optimized: Formula-based calculation instead of large storage arrays
 * - Deterministic: Same inputs always produce same outputs
 *
 * Emission Schedule:
 * - Phase A (Week 1-12): Fixed 37.5M PAIMON/week
 * - Phase B (Week 13-248): Exponential decay from 37.5M to 4.327M
 * - Phase C (Week 249-352): Fixed 4.327M PAIMON/week
 * - Total emissions: ~10B PAIMON over 352 weeks (6.77 years)
 *
 * Budget Allocation:
 * - Debt channel: 10% (liquidation incentives)
 * - LP total: 70% (liquidity mining)
 *   - LP Pairs: Governance-adjustable (default 60% of LP)
 *   - Stability Pool: Governance-adjustable (default 40% of LP)
 * - Eco channel: 20% (ecosystem development, grants, partnerships)
 *
 * Security:
 * - Ownable: Only owner can adjust LP split parameters
 * - Parameter validation: LP split must sum to exactly 100%
 * - Range validation: Week number must be in [1, 352]
 * - Immutable phases: Emission schedule cannot be changed after deployment
 *
 * Gas Optimization:
 * - No large storage arrays (Phase B calculated on-the-fly)
 * - Immutable constants for fixed values
 * - View functions only (no state changes on budget queries)
 * - Efficient power calculation using logarithms
 *
 * Integration:
 * - GaugeController: Calls getWeeklyBudget to distribute LP rewards
 * - RewardDistributor: Calls getWeeklyBudget for veNFT holder rewards
 * - Treasury: Calls getWeeklyBudget for eco fund allocation
 * - LiquidationManager: Calls getWeeklyBudget for liquidation incentives
 *
 * Monitoring (P3-001):
 * - EmissionManager is a pure calculation contract with no state-changing functions
 * - Actual emission allocation tracking is delegated to consuming contracts:
 *   • GaugeController emits distribution events for LP rewards
 *   • RewardDistributor emits distribution events for veNFT rewards
 *   • Treasury emits deposit/withdrawal events for eco fund
 *   • LiquidationManager emits liquidation events with reward amounts
 * - This design avoids redundant event emissions and ensures accountability
 *   at the point of actual token distribution, not budget calculation
 */
contract EmissionManager is Ownable {
    // ==================== Constants ====================

    /// @notice Phase A fixed weekly emission (Week 1-12)
    /// @dev Per whitepaper specification
    ///      Maintains original ratio: Phase A / Phase C ≈ 8.67
    uint256 public constant PHASE_A_WEEKLY = 37_500_000 * 1e18; // 37.5M PAIMON

    /// @notice Phase C fixed weekly emission (Week 249-352)
    /// @dev Per whitepaper specification
    uint256 public constant PHASE_C_WEEKLY = 4_326_923 * 1e18; // 4.327M PAIMON

    /// @notice Last week of Phase A
    uint256 public constant PHASE_A_END = 12;

    /// @notice Last week of Phase B
    uint256 public constant PHASE_B_END = 248;

    /// @notice Last week of Phase C (final week of emission)
    uint256 public constant PHASE_C_END = 352;

    /// @notice Basis points denominator (100% = 10000 bps)
    uint256 public constant BASIS_POINTS = 10000;

    /// @notice Exponential decay rate for Phase-B (0.985 = 98.5%)
    uint256 public constant DECAY_RATE_BPS = 9850; // 0.985 in basis points

    // Phase-A channel allocation (Week 1-12): 30% debt, 60% LP, 10% eco
    uint256 private constant PHASE_A_DEBT_BPS = 3000; // 30%
    uint256 private constant PHASE_A_LP_BPS = 6000; // 60%
    uint256 private constant PHASE_A_ECO_BPS = 1000; // 10%

    // Phase-B channel allocation (Week 13-248): 50% debt, 37.5% LP, 12.5% eco
    uint256 private constant PHASE_B_DEBT_BPS = 5000; // 50%
    uint256 private constant PHASE_B_LP_BPS = 3750; // 37.5%
    uint256 private constant PHASE_B_ECO_BPS = 1250; // 12.5%

    // Phase-C channel allocation (Week 249-352): 55% debt, 35% LP, 10% eco
    uint256 private constant PHASE_C_DEBT_BPS = 5500; // 55%
    uint256 private constant PHASE_C_LP_BPS = 3500; // 35%
    uint256 private constant PHASE_C_ECO_BPS = 1000; // 10%

    /// @notice Precision multiplier for decay calculations (to avoid floating point)
    uint256 private constant PRECISION = 1e18;

    /// @notice Phase-B emission lookup table (236 weeks: Week 13-248)
    /// @dev Pre-computed values for O(1) gas-optimized lookup (Task P1-001)
    ///      Generated by scripts/generate-phase-b-table.py
    ///      Formula: E_B(t) = 37,500,000 * 0.985^t, t=1..236
    ///      Index 0 = Week 13, Index 235 = Week 248
    ///      Note: Cannot use 'constant' with arrays in Solidity, so declared as private storage
    uint256[236] private PHASE_B_EMISSIONS = [
        36937499999999998205886464, 36383437499999998812618752, 35837685937499999066652672,
        35300120648437500605366272, 34770618838710935326031872, 34249059556130269062758400, 33735323662788314489946112,
        33229293807846491189936128, 32730854400728792297373696, 32239891584717863161692160, 31756293210947093174157312,
        31279948812782888193884160, 30810749580591140683382784, 30348588336882275441442816, 29893359511829042662735872,
        29444959119151603715670016, 29003284732364330475978752, 28568235461378863607578624, 28139711929458181340659712,
        27717616250516305742921728, 27301852006758561242677248, 26892324226657184198426624, 26488939363257327122644992,
        26091605272808466807783424, 25700231193716341566603264, 25314727725810594338570240, 24935006809923435852988416,
        24560981707774581910011904, 24192566982157959358840832, 23829678477425593748029440, 23472233300264207586951168,
        23120149800760242841059328, 22773347553748840894955520, 22431747340442605275054080, 22095271130335968128663552,
        21763842063380925621731328, 21437384432430216655142912, 21115823665943761601429504, 20799086310954602965499904,
        20487100016290284930334720, 20179793516045930871128064, 19877096613305239266656256, 19578940164105661386326016,
        19285256061644079965929472, 18995977220719419754283008, 18711037562408622960410624, 18430371998972493497892864,
        18153916418987907480551424, 17881607672703087139618816, 17613383557612542990745600, 17349182804248351356223488,
        17088945062184627621330944, 16832610886251860182695936, 16580121722958079284215808, 16331419897113708234539008,
        16086448598657002482171904, 15845151869677149527998464, 15607474591631990985850880, 15373362472757508490395648,
        15142762035666146432122880, 14915620605131156168376320, 14691886296054187161550848, 14471508001613374117904384,
        14254435381589173495398400, 14040618850865335892967424, 13830009568102353588977664, 13622559424580819133399040,
        13418221033212109423378432, 13216947717713923508535296, 13018693501948217404686336, 12823413099418993295360000,
        12631061902927707590623232, 12441595974383791729803264, 12254972034768035165241344, 12071147454246513392222208,
        11890080242432816904667136, 11711729038796324071276544, 11536053103214379038408704, 11363012306666162751537152,
        11192567122066171888664576, 11024678615235177549398016, 10859308436006649360023552, 10696418809466551198023680,
        10535972527324552178434048, 10377932939414683659534336, 10222263945323464435433472, 10068929986143610772389888,
        9917896036351456535642112, 9769127595806185031204864, 9622590681869093372428288, 9478251821641054346543104,
        9336078044316438466920448, 9196036873651692324782080, 9058096320546917530468352, 8922224875738714003734528,
        8788391502602632976924672, 8656565630063593664806912, 8526717145612637955948544, 8398816388428450093858816,
        8272834142602023218970624, 8148741630462991007744000, 8026510506006047082151936, 7906112848415956467187712,
        7787521155689715987382272, 7670708338354370027454464, 7555647713279055727951872, 7442312997579868866609152,
        7330678302616171740921856, 7220718128076927860211712, 7112407356155773883252736, 7005721245813437232054272,
        6900635427126236661415936, 6797125895719342934327296, 6695169007283551915212800, 6594741472174298770702336,
        6495820350091683843538944, 6398383044840308682522624, 6302407299167703531520000, 6207871189680188783853568,
        6114753121834986064838656, 6023031825007460103487488, 5932686347632348932079616, 5843696052417863574618112,
        5756040611631595293507584, 5669700002457121219149824, 5584654502420265759145984, 5500884684883960151408640,
        5418371414610701581287424, 5337095843391539194626048, 5257039405740666810007552, 5178183814654557178298368,
        5100511057434739067584512, 5024003391573217519861760, 4948643340699618156478464, 4874413690589124598169600,
        4801297485230288266067968, 4729278022951833853493248, 4658338852607555841032192, 4588463769818442766483456,
        4519636813271165961240576, 4451842261072098455715840, 4385064627156016334635008, 4319288657748676162093056,
        4254499327882446527004672, 4190681837964209877417984, 4127821610394745980321792, 4065904286238824986574848,
        4004915721945242912423936, 3944841986116064024461312, 3885669356324322266841088, 3827384315979458028765184,
        3769973551239766013378560, 3713423947971169697660928, 3657722588751601902551040, 3602856749920327900856320,
        3548813898671522794438656, 3495581690191450325647360, 3443147964838578476810240, 3391500745365999423848448,
        3340628234185509598920704, 3290518810672727091838976, 3241161028512635968028672, 3192543613084946543935488,
        3144655458888671935070208, 3097485627005342129848320, 3051023342600261809995776, 3005257992461257866739712,
        2960179122574338939682816, 2915776435735723664998400, 2872039789199687877132288, 2828959192361692819357696,
        2786524804476267155947520, 2744726932409123094921216, 2703556028422986393452544, 2663002687996641492860928,
        2623057647676691956367360, 2583711782961541214633984, 2544956106217118488330240, 2506781764623861335195648,
        2469180038154503313162240, 2432142337582185723199488, 2395660202518452929298432, 2359725299480676257497088,
        2324329419988465971363840, 2289464478688639142854656, 2255122511508309358411776, 2221295673835684601266176,
        2187976238728149450358784, 2155156595147227063648256, 2122829246220018829492224, 2090986807526718227611648,
        2059622005413817452855296, 2028727675332610322595840, 1998296760202621026828288, 1968322308799581837590528,
        1938797474167588263034880, 1909715512055074090123264, 1881069779374247954612224, 1852853732683634419171328,
        1825060926693379720347648, 1797685012792978855428096, 1770719737601084169912320, 1744158941537067954339840,
        1717996557414012096086016, 1692226609052801858273280, 1666843209917009447878656, 1641840561768254377295872,
        1617212953341730844835840, 1592954759041604707680256, 1569060437655980741754880, 1545524531091140882989056,
        1522341663124773740216320, 1499506538177901979762688, 1477013940105233777557504, 1454858731003655139360768,
        1433035850038600290795520, 1411540312288021232746496, 1390367207603700911570944, 1369511699489645326761984,
        1348969023997300636123136, 1328734488637341050077184, 1308803471307781091360768, 1289171419238164454178816,
        1269833847949591897440256, 1250786340230347922341888, 1232024545126892695453696, 1213544176949989168119808,
        1195341014295739369521152, 1177410899081303313874944, 1159749735595083760140288, 1142353489561157512462336,
        1125218187217740123602944, 1108339914409473950613504, 1091714815693331927924736, 1075339093457931838947328,
        1059209007056062846599168
    ];

    // ==================== State Variables ====================

    /// @notice LP Pairs allocation within LP total (basis points)
    /// @dev Default: 6000 bps = 60% of LP total = 42% of total budget
    uint16 public lpPairsBps = 6000;

    /// @notice Stability Pool allocation within LP total (basis points)
    /// @dev Default: 4000 bps = 40% of LP total = 28% of total budget
    uint16 public stabilityPoolBps = 4000;

    // ==================== Events ====================

    /// @notice Emitted when LP split parameters are updated
    event LpSplitParamsUpdated(uint16 lpPairsBps, uint16 stabilityPoolBps);

    // ==================== Constructor ====================

    constructor() Ownable(msg.sender) {}

    // ==================== Core Functions ====================

    /**
     * @notice Get weekly emission budget for a specific week
     * @param week Week number (1-indexed, must be in [1, 352])
     * @return debt Debt channel budget (liquidation incentives)
     * @return lpPairs LP Pairs channel budget (liquidity mining)
     * @return stabilityPool Stability Pool channel budget
     * @return eco Eco channel budget (ecosystem development)
     * @dev Gas cost:
     *      - Phase A/C: ~5-10K gas (constant lookup)
     *      - Phase B: ~15-20K gas (exponential calculation)
     */
    function getWeeklyBudget(uint256 week)
        external
        view
        returns (uint256 debt, uint256 lpPairs, uint256 stabilityPool, uint256 eco)
    {
        require(week >= 1 && week <= PHASE_C_END, "Week out of range [1, 352]");

        uint256 totalBudget;

        // Phase A: Fixed 37.5M per week (Week 1-12)
        if (week <= PHASE_A_END) {
            totalBudget = PHASE_A_WEEKLY;
        }
        // Phase B: Exponential decay (Week 13-248)
        else if (week <= PHASE_B_END) {
            totalBudget = _calculatePhaseBEmission(week);
        }
        // Phase C: Fixed 4.327M per week (Week 249-352)
        else {
            totalBudget = PHASE_C_WEEKLY;
        }

        // Allocate to four channels with phase-specific ratios
        (debt, lpPairs, stabilityPool, eco) = _allocateBudget(totalBudget, week);
    }

    /**
     * @notice Calculate total PAIMON emission across all 352 weeks
     * @return totalEmission Total emission amount (~3.29B PAIMON)
     * @dev Computes sum of all weekly budgets from Week 1 to Week 352.
     *      Result depends on current lpPairsBps and stabilityPoolBps settings.
     *      Expected total: ~3,292,945,267 PAIMON (with exponential decay r=0.985)
     *
     *      Gas cost: ~1.2M gas (calls getWeeklyBudget 352 times)
     *      Use this function for validation and monitoring, not for frequent queries.
     */
    function getTotalEmission() external view returns (uint256 totalEmission) {
        for (uint256 week = 1; week <= PHASE_C_END; week++) {
            (uint256 debt, uint256 lpPairs, uint256 stabilityPool, uint256 eco) = this.getWeeklyBudget(week);
            totalEmission += (debt + lpPairs + stabilityPool + eco);
        }
    }

    /**
     * @notice Get rounding dust for a specific week (Task P1-002)
     * @param week Week number (1-indexed, must be in [1, 352])
     * @return dust Rounding dust amount collected in debt channel
     * @dev Dust is the difference between totalBudget and sum of theoretical channel allocations.
     *      This function makes dust traceable for auditing and verification.
     *
     *      Calculation:
     *      1. Get actual allocations from getWeeklyBudget (includes collected dust)
     *      2. Calculate theoretical allocations without dust collection
     *      3. dust = totalBudget - theoretical_allocated
     *
     *      The debt channel receives this dust to ensure perfect conservation.
     *
     *      Gas cost: ~10-20K gas (similar to getWeeklyBudget)
     */
    function getWeeklyDust(uint256 week) external view returns (uint256 dust) {
        require(week >= 1 && week <= PHASE_C_END, "Week out of range [1, 352]");

        (uint256 debt, uint256 lpPairs, uint256 stabilityPool, uint256 eco) = this.getWeeklyBudget(week);

        uint256 totalBudget = debt + lpPairs + stabilityPool + eco;

        // Get phase-specific allocation ratios
        uint256 debtBps;
        uint256 lpBps;
        uint256 ecoBps;

        if (week <= PHASE_A_END) {
            debtBps = PHASE_A_DEBT_BPS;
            lpBps = PHASE_A_LP_BPS;
            ecoBps = PHASE_A_ECO_BPS;
        } else if (week <= PHASE_B_END) {
            debtBps = PHASE_B_DEBT_BPS;
            lpBps = PHASE_B_LP_BPS;
            ecoBps = PHASE_B_ECO_BPS;
        } else {
            debtBps = PHASE_C_DEBT_BPS;
            lpBps = PHASE_C_LP_BPS;
            ecoBps = PHASE_C_ECO_BPS;
        }

        // Calculate theoretical allocations (before dust collection)
        uint256 theoreticalDebt = (totalBudget * debtBps) / BASIS_POINTS;
        uint256 theoreticalEco = (totalBudget * ecoBps) / BASIS_POINTS;
        uint256 theoreticalLpTotal = (totalBudget * lpBps) / BASIS_POINTS;
        uint256 theoreticalLpPairs = (theoreticalLpTotal * lpPairsBps) / BASIS_POINTS;
        uint256 theoreticalStabilityPool = (theoreticalLpTotal * stabilityPoolBps) / BASIS_POINTS;

        uint256 theoreticalAllocated =
            theoreticalDebt + theoreticalLpPairs + theoreticalStabilityPool + theoreticalEco;

        // Dust is the difference (rounding error)
        dust = totalBudget - theoreticalAllocated;
    }

    /**
     * @notice Calculate total dust across all 352 weeks (Task P1-002)
     * @return totalDust Total rounding dust amount (~<1000 PAIMON)
     * @dev Sums up dust from all weeks to verify cumulative rounding error is minimal.
     *
     *      Expected total dust: <1000 PAIMON (<0.00003% of total emissions)
     *
     *      This function is useful for:
     *      - Audit verification
     *      - Quality assurance testing
     *      - Economic model validation
     *
     *      Gas cost: ~1.5M gas (calls getWeeklyDust 352 times)
     *      Use this function for validation and monitoring, not for frequent queries.
     */
    function getTotalDust() external view returns (uint256 totalDust) {
        for (uint256 week = 1; week <= PHASE_C_END; week++) {
            totalDust += this.getWeeklyDust(week);
        }
    }

    /**
     * @notice Set LP secondary split parameters (governance function)
     * @param _lpPairsBps LP Pairs allocation in basis points (0-10000)
     * @param _stabilityPoolBps Stability Pool allocation in basis points (0-10000)
     * @dev Requirements:
     *      - Only callable by owner (Timelock in production)
     *      - Sum must equal exactly 10000 bps (100%)
     *      - Changes apply immediately to all future getWeeklyBudget calls
     */
    function setLpSplitParams(uint16 _lpPairsBps, uint16 _stabilityPoolBps) external onlyOwner {
        require(_lpPairsBps + _stabilityPoolBps == BASIS_POINTS, "LP split must sum to 100%");

        lpPairsBps = _lpPairsBps;
        stabilityPoolBps = _stabilityPoolBps;

        emit LpSplitParamsUpdated(_lpPairsBps, _stabilityPoolBps);
    }

    // ==================== Internal Functions ====================

    /**
     * @notice Get Phase B emission from pre-computed lookup table (Task P1-001)
     * @param week Week number (must be in [13, 248])
     * @return emission Weekly emission amount
     * @dev O(1) gas-optimized lookup replacing O(log n) formula calculation.
     *      Uses PHASE_B_EMISSIONS lookup table generated offline.
     *
     * Gas optimization:
     * - Previous: O(log n) using _fastPower() (~15-20K gas)
     * - Current: O(1) array access (~5K gas)
     * - Savings: ~10-15K gas per call
     *
     * Accuracy:
     * - Pre-computed with full Python precision (float64)
     * - Matches formula E(w) = 37,500,000 * 0.985^(w - 12) within 0.1%
     */
    function _calculatePhaseBEmission(uint256 week) private view returns (uint256) {
        require(week > PHASE_A_END && week <= PHASE_B_END, "Week not in Phase B");

        // O(1) lookup: Week 13 = index 0, Week 248 = index 235
        uint256 index = week - PHASE_A_END - 1;
        return PHASE_B_EMISSIONS[index];
    }

    /**
     * @notice Fast exponentiation (exponentiation by squaring)
     * @param base Base value in basis points (e.g., 9850 for 0.985)
     * @param denominator Denominator for fixed-point (e.g., 10000 for basis points)
     * @param exponent Exponent value
     * @return result (base/denominator)^exponent scaled by PRECISION (1e18)
     * @dev Computes (base/denominator)^exponent with fixed-point precision.
     *      Uses binary exponentiation for O(log n) complexity.
     *      Example: _fastPower(9850, 10000, 5) returns 0.985^5 * 1e18 ≈ 0.927 * 1e18
     */
    function _fastPower(uint256 base, uint256 denominator, uint256 exponent) private pure returns (uint256) {
        if (exponent == 0) {
            return PRECISION; // x^0 = 1
        }

        uint256 result = PRECISION; // Start with 1.0 in fixed-point
        uint256 currentBase = (base * PRECISION) / denominator; // Convert base to fixed-point

        while (exponent > 0) {
            if (exponent % 2 == 1) {
                // If exponent is odd, multiply result by current base
                result = (result * currentBase) / PRECISION;
            }
            // Square the base
            currentBase = (currentBase * currentBase) / PRECISION;
            // Halve the exponent
            exponent /= 2;
        }

        return result;
    }

    /**
     * @notice Allocate total budget to four channels with phase-specific ratios
     * @param totalBudget Total weekly budget to allocate
     * @param week Week number to determine phase-specific allocation
     * @return debt Debt channel allocation (phase-dependent: 30%/50%/55%)
     * @return lpPairs LP Pairs channel allocation (governance-adjustable split)
     * @return stabilityPool Stability Pool channel allocation (governance-adjustable split)
     * @return eco Eco channel allocation (phase-dependent: 10%/12.5%/10%)
     * @dev Phase-specific allocation:
     *      Phase-A (Week 1-12): 30% debt, 60% LP, 10% eco
     *      Phase-B (Week 13-248): 50% debt, 37.5% LP, 12.5% eco
     *      Phase-C (Week 249-352): 55% debt, 35% LP, 10% eco
     *
     *      LP total is further split between lpPairs and stabilityPool using governance-adjustable parameters.
     *      Dust collection: Any rounding error is added to debt channel to ensure exact conservation.
     */
    function _allocateBudget(uint256 totalBudget, uint256 week)
        private
        view
        returns (uint256 debt, uint256 lpPairs, uint256 stabilityPool, uint256 eco)
    {
        uint256 debtBps;
        uint256 lpBps;
        uint256 ecoBps;

        // Determine phase-specific allocation ratios
        if (week <= PHASE_A_END) {
            // Phase-A: 30% debt, 60% LP, 10% eco
            debtBps = PHASE_A_DEBT_BPS;
            lpBps = PHASE_A_LP_BPS;
            ecoBps = PHASE_A_ECO_BPS;
        } else if (week <= PHASE_B_END) {
            // Phase-B: 50% debt, 37.5% LP, 12.5% eco
            debtBps = PHASE_B_DEBT_BPS;
            lpBps = PHASE_B_LP_BPS;
            ecoBps = PHASE_B_ECO_BPS;
        } else {
            // Phase-C: 55% debt, 35% LP, 10% eco
            debtBps = PHASE_C_DEBT_BPS;
            lpBps = PHASE_C_LP_BPS;
            ecoBps = PHASE_C_ECO_BPS;
        }

        // Calculate channel allocations
        debt = (totalBudget * debtBps) / BASIS_POINTS;
        eco = (totalBudget * ecoBps) / BASIS_POINTS;

        // LP secondary split (governance-adjustable)
        // Task P2-001: Fix precision loss - combine multiplications before division
        lpPairs = (totalBudget * lpBps * lpPairsBps) / (BASIS_POINTS * BASIS_POINTS);
        stabilityPool = (totalBudget * lpBps * stabilityPoolBps) / (BASIS_POINTS * BASIS_POINTS);

        // Dust collection: Add any rounding error to debt channel
        uint256 allocated = debt + lpPairs + stabilityPool + eco;
        if (allocated < totalBudget) {
            debt += (totalBudget - allocated);
        }
    }
}
