#!/usr/bin/env python3
"""
Generate Phase-B emission lookup table for EmissionManager.sol (Task P1-001)

Purpose:
- Pre-compute 236 weeks of exponential decay values
- Convert from O(log n) formula calculation to O(1) array lookup
- Maintains precision while optimizing gas costs

Formula:
E_B(t) = PHASE_A_WEEKLY * r^t, where:
- PHASE_A_WEEKLY = 37,500,000 PAIMON
- r = 0.985 (decay rate)
- t = 1..236 (Week 13 uses t=1, Week 248 uses t=236)

Output:
- Solidity array declaration
- CSV for validation
- Summary statistics
"""

PHASE_A_WEEKLY = 37_500_000  # PAIMON
DECAY_RATE = 0.985
PRECISION = 10**18  # Solidity 1e18

def generate_phase_b_table():
    """Generate Phase-B emission values for weeks 13-248 (236 values)"""
    emissions = []

    for t in range(1, 237):  # t=1 corresponds to Week 13
        # E_B(t) = PHASE_A_WEEKLY * r^t  (NOT r^(t-1))
        # Week 13 (t=1): 37.5M * 0.985^1 = 36.9375M
        # Week 14 (t=2): 37.5M * 0.985^2 = 36.383M
        emission = PHASE_A_WEEKLY * (DECAY_RATE ** t)
        # Convert to integer with 18 decimals
        emission_wei = int(emission * PRECISION)
        emissions.append(emission_wei)

    return emissions

def format_solidity_array(emissions):
    """Format emissions as Solidity uint256 array"""
    lines = ["    // Phase-B emission lookup table (236 weeks: Week 13-248)"]
    lines.append("    // Generated by scripts/generate-phase-b-table.py")
    lines.append("    // Formula: E_B(t) = 37,500,000 * 0.985^t, t=1..236")
    lines.append("    uint256[236] private constant PHASE_B_EMISSIONS = [")

    # Format in groups of 4 values per line for readability
    for i in range(0, len(emissions), 4):
        chunk = emissions[i:i+4]
        formatted = ", ".join(f"{e}" for e in chunk)

        if i + 4 < len(emissions):
            lines.append(f"        {formatted},")
        else:
            lines.append(f"        {formatted}")

    lines.append("    ];")
    return "\n".join(lines)

def save_csv(emissions):
    """Save emissions to CSV for validation"""
    with open("phase-b-emissions.csv", "w") as f:
        f.write("Week,Emission_PAIMON,Emission_Wei\n")
        for i, emission_wei in enumerate(emissions):
            week = i + 13  # Week 13 is index 0
            emission_paimon = emission_wei / PRECISION
            f.write(f"{week},{emission_paimon:.2f},{emission_wei}\n")

def print_summary(emissions):
    """Print summary statistics"""
    print("=" * 70)
    print("Phase-B Emission Lookup Table Generation (Task P1-001)")
    print("=" * 70)
    print(f"Total weeks: {len(emissions)}")
    print(f"Week range: 13-248")
    print(f"Decay rate: {DECAY_RATE}")
    print()
    print("Key values:")
    print(f"  Week 13 (index 0):   {emissions[0] / PRECISION:>15,.0f} PAIMON")
    print(f"  Week 100 (index 87): {emissions[87] / PRECISION:>15,.0f} PAIMON")
    print(f"  Week 248 (index 235):{emissions[235] / PRECISION:>15,.0f} PAIMON")
    print()
    total_phase_b = sum(emissions) / PRECISION
    print(f"Total Phase-B emissions: {total_phase_b:>15,.0f} PAIMON")
    print("=" * 70)

if __name__ == "__main__":
    # Generate emissions
    emissions = generate_phase_b_table()

    # Print summary
    print_summary(emissions)

    # Save CSV
    save_csv(emissions)
    print(f"\n✅ CSV saved to: phase-b-emissions.csv")

    # Print Solidity array
    print("\n" + "=" * 70)
    print("Solidity Array Declaration (copy to EmissionManager.sol):")
    print("=" * 70)
    print(format_solidity_array(emissions))
    print()
