"""Add points system tables

Revision ID: 3209aa090f79
Revises: 88364eb7f7ec
Create Date: 2025-11-15 17:30:29.735105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3209aa090f79'
down_revision: Union[str, Sequence[str], None] = '88364eb7f7ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points_balance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.Column('total_earned', sa.BigInteger(), nullable=False),
    sa.Column('total_spent', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_balance_user_id'), 'points_balance', ['user_id'], unique=True)
    op.create_table('points_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('balance_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('balance_after', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=False),
    sa.Column('transaction_metadata', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['balance_id'], ['points_balance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_transactions_balance_id'), 'points_transactions', ['balance_id'], unique=False)
    op.create_index(op.f('ix_points_transactions_reference_id'), 'points_transactions', ['reference_id'], unique=False)
    op.create_index(op.f('ix_points_transactions_transaction_id'), 'points_transactions', ['transaction_id'], unique=True)
    op.create_index('ix_points_tx_balance_created', 'points_transactions', ['balance_id', 'created_at'], unique=False)
    op.create_index('ix_points_tx_type_source', 'points_transactions', ['type', 'source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_points_tx_type_source', table_name='points_transactions')
    op.drop_index('ix_points_tx_balance_created', table_name='points_transactions')
    op.drop_index(op.f('ix_points_transactions_transaction_id'), table_name='points_transactions')
    op.drop_index(op.f('ix_points_transactions_reference_id'), table_name='points_transactions')
    op.drop_index(op.f('ix_points_transactions_balance_id'), table_name='points_transactions')
    op.drop_table('points_transactions')
    op.drop_index(op.f('ix_points_balance_user_id'), table_name='points_balance')
    op.drop_table('points_balance')
    # ### end Alembic commands ###
