"""add portfolio_cache table

Revision ID: 8c4ecbce1f76
Revises: 60539cfbacbd
Create Date: 2025-11-14 20:54:35.065813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c4ecbce1f76'
down_revision: Union[str, Sequence[str], None] = '60539cfbacbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.Enum('LP_POSITIONS', 'VAULT_POSITIONS', 'VENFT_POSITIONS', 'PORTFOLIO_SUMMARY', name='datatype'), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_portfolio_cache_expires_at', 'portfolio_cache', ['expires_at'], unique=False)
    op.create_index('idx_portfolio_cache_user_data_type', 'portfolio_cache', ['user_id', 'data_type'], unique=False)
    op.create_index(op.f('ix_portfolio_cache_user_id'), 'portfolio_cache', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_cache_user_id'), table_name='portfolio_cache')
    op.drop_index('idx_portfolio_cache_user_data_type', table_name='portfolio_cache')
    op.drop_index('idx_portfolio_cache_expires_at', table_name='portfolio_cache')
    op.drop_table('portfolio_cache')
    # ### end Alembic commands ###
